# lea override for otelcol-ebpf-profiler.
log_level: 1
programs:
  default:
    command: |
      bpfopt --pass lea --input ${INPUT} --output ${OUTPUT} --report ${REPORT} --prog-type ${PROG_TYPE} --target ${TARGET}
hashes:
  32bd350b425c882e:
    command: |
      bpfopt --pass lea --input ${INPUT} --output ${OUTPUT} --report ${REPORT} --prog-type ${PROG_TYPE} --target ${TARGET} -- --kinsn-mode all=disable
