schema_version: 1
scheduler:
  max_parallel_jobs: 15
jobs:
- id: target-0001:baseline-compile
  type: test_run
  execution: parallel
  runtime: kernel
  program: /home/yunwei37/workspace/bpf-benchmark/corpus/build/calico/from_wep_debug.bpf.o
  program_name: calico_tc_skb_new_flow_entrypoint
  io_mode: packet
  repeat: 50
  compile_only: true
  input_size: 64
  btf_custom_path: /home/yunwei37/workspace/bpf-benchmark/vendor/linux-framework/vmlinux
  prepared_key: target-0001:baseline-prepared
  prepared_group: chunk-0000:baseline
- id: target-0001:baseline-run
  type: test_run
  execution: serial
  runtime: kernel
  program: /home/yunwei37/workspace/bpf-benchmark/corpus/build/calico/from_wep_debug.bpf.o
  program_name: calico_tc_skb_new_flow_entrypoint
  io_mode: packet
  repeat: 50
  compile_only: false
  input_size: 64
  btf_custom_path: /home/yunwei37/workspace/bpf-benchmark/vendor/linux-framework/vmlinux
  prepared_ref: target-0001:baseline-prepared
  prepared_group: chunk-0000:baseline
- id: target-0001:pgo-warmup
  type: test_run
  execution: serial
  runtime: kernel
  program: /home/yunwei37/workspace/bpf-benchmark/corpus/build/calico/from_wep_debug.bpf.o
  program_name: calico_tc_skb_new_flow_entrypoint
  io_mode: packet
  repeat: 10
  compile_only: false
  input_size: 64
  btf_custom_path: /home/yunwei37/workspace/bpf-benchmark/vendor/linux-framework/vmlinux
- id: target-0001:rejit-compile
  type: test_run
  execution: parallel
  runtime: kernel-rejit
  program: /home/yunwei37/workspace/bpf-benchmark/corpus/build/calico/from_wep_debug.bpf.o
  program_name: calico_tc_skb_new_flow_entrypoint
  io_mode: packet
  repeat: 50
  compile_only: true
  input_size: 64
  btf_custom_path: /home/yunwei37/workspace/bpf-benchmark/vendor/linux-framework/vmlinux
  daemon_socket: /tmp/bpfrejit-guest-363.sock
  passes:
  - map_inline
  - const_prop
  - dce
  - wide_mem
  - rotate
  - cond_select
  - extract
  - endian_fusion
  - bulk_memory
  - bounds_check_merge
  - skb_load_bytes
  - branch_flip
  prepared_key: target-0001:rejit-prepared
  prepared_group: chunk-0000:rejit
- id: target-0001:rejit-run
  type: test_run
  execution: serial
  runtime: kernel-rejit
  program: /home/yunwei37/workspace/bpf-benchmark/corpus/build/calico/from_wep_debug.bpf.o
  program_name: calico_tc_skb_new_flow_entrypoint
  io_mode: packet
  repeat: 50
  compile_only: false
  input_size: 64
  btf_custom_path: /home/yunwei37/workspace/bpf-benchmark/vendor/linux-framework/vmlinux
  daemon_socket: /tmp/bpfrejit-guest-363.sock
  passes:
  - map_inline
  - const_prop
  - dce
  - wide_mem
  - rotate
  - cond_select
  - extract
  - endian_fusion
  - bulk_memory
  - bounds_check_merge
  - skb_load_bytes
  - branch_flip
  prepared_ref: target-0001:rejit-prepared
  prepared_group: chunk-0000:rejit
