schema_version: 1
scheduler:
  max_parallel_jobs: 15
jobs:
- id: target-0001:baseline-compile
  type: test_run
  execution: parallel
  runtime: kernel
  program: /home/yunwei37/workspace/bpf-benchmark/corpus/build/bcc/libbpf-tools/tcprtt.bpf.o
  program_name: tcp_rcv
  io_mode: context
  repeat: 50
  compile_only: true
  btf_custom_path: /home/yunwei37/workspace/bpf-benchmark/vendor/linux-framework/vmlinux
- id: target-0001:baseline-run
  type: test_run
  execution: serial
  runtime: kernel-attach
  program: /home/yunwei37/workspace/bpf-benchmark/corpus/build/bcc/libbpf-tools/tcprtt.bpf.o
  program_name: tcp_rcv
  io_mode: map
  repeat: 50
  compile_only: false
  btf_custom_path: /home/yunwei37/workspace/bpf-benchmark/vendor/linux-framework/vmlinux
- id: target-0001:rejit-compile
  type: test_run
  execution: parallel
  runtime: kernel-rejit
  program: /home/yunwei37/workspace/bpf-benchmark/corpus/build/bcc/libbpf-tools/tcprtt.bpf.o
  program_name: tcp_rcv
  io_mode: context
  repeat: 50
  compile_only: true
  btf_custom_path: /home/yunwei37/workspace/bpf-benchmark/vendor/linux-framework/vmlinux
  daemon_socket: /tmp/bpfrejit-guest-362.sock
  passes:
  - map_inline
  - const_prop
  - dce
  - wide_mem
  - rotate
  - cond_select
  - extract
  - endian_fusion
  - bulk_memory
  - bounds_check_merge
  - skb_load_bytes
  - branch_flip
- id: target-0001:rejit-run
  type: test_run
  execution: serial
  runtime: kernel-attach-rejit
  program: /home/yunwei37/workspace/bpf-benchmark/corpus/build/bcc/libbpf-tools/tcprtt.bpf.o
  program_name: tcp_rcv
  io_mode: map
  repeat: 50
  compile_only: false
  btf_custom_path: /home/yunwei37/workspace/bpf-benchmark/vendor/linux-framework/vmlinux
  daemon_socket: /tmp/bpfrejit-guest-362.sock
  passes:
  - map_inline
  - const_prop
  - dce
  - wide_mem
  - rotate
  - cond_select
  - extract
  - endian_fusion
  - bulk_memory
  - bounds_check_merge
  - skb_load_bytes
  - branch_flip
