apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: bpf-benchmark-tetragon-e2e-kprobes
spec:
  kprobes:
    - call: security_bprm_check
      syscall: false
    - call: security_file_open
      syscall: false
    - call: security_socket_connect
      syscall: false
